// Sample data for Bear Witness Dashboard

const now = Date.now();
const day = 86400000;
const hour = 3600000;

export const sampleClients = [
  {
    id: 'client-th',
    name: "Ted's Health",
    sector: 'Health and Wellness',
    platforms: ['Instagram', 'TikTok', 'YouTube', 'Newsletter'],
    partnershipType: 'Internal Brand',
    status: 'Active',
    budgetRange: '15-50k',
    priority: 'High',
    contactName: 'Sarah Mitchell',
    contactEmail: 'sarah@tedshealth.com',
    contactPhone: '+44 7700 900123',
    website: 'https://tedshealth.com',
    socialHandles: {
      instagram: '@tedshealth',
      tiktok: '@tedshealth',
      youtube: '@TedsHealthOfficial',
    },
    brandVoice: 'Authoritative yet approachable. Expert-led health content grounded in science but delivered with warmth. Bear Grylls energy — adventurous, resilient, no-nonsense.',
    targetAudience: 'Health-conscious adults 25-55, predominantly male, interested in supplements, fitness, and longevity. UK and US primary markets.',
    keyMessages: [
      'Science-backed wellness solutions',
      'Adventure-ready health',
      'Natural ingredients, proven results',
    ],
    goals: 'Grow Instagram to 100k followers by Q3. Launch YouTube series on gut health. Drive 25% increase in supplement subscriptions.',
    notes: 'Monthly content calendar review with Sarah. Bear available for filming first week of each month.',
    createdAt: now - 90 * day,
    updatedAt: now - 2 * day,
  },
  {
    id: 'client-w2',
    name: 'Water2',
    sector: 'Sustainability',
    platforms: ['Instagram', 'LinkedIn', 'X/Twitter', 'Facebook'],
    partnershipType: 'Equity Partner',
    status: 'Active',
    budgetRange: '5-15k',
    priority: 'Medium',
    contactName: 'James Thornton',
    contactEmail: 'james@water2.co',
    contactPhone: '+44 7700 900456',
    website: 'https://water2.co',
    socialHandles: {
      instagram: '@water2official',
      linkedin: 'water2',
      twitter: '@water2co',
    },
    brandVoice: 'Purpose-driven and optimistic. Environmental urgency without doom. Solution-focused, community-minded. Clean, modern, trustworthy.',
    targetAudience: 'Environmentally conscious consumers 20-45, B2B sustainability officers, eco-friendly lifestyle enthusiasts. UK primary, expanding to EU.',
    keyMessages: [
      'Clean water for every community',
      'Sustainable hydration solutions',
      'Every bottle funds clean water projects',
    ],
    goals: 'Build B2B pipeline through LinkedIn thought leadership. Increase Instagram engagement rate to 4%. Launch Earth Day campaign.',
    notes: 'James prefers async communication. Quarterly strategy reviews. Earth Day is a major campaign moment.',
    createdAt: now - 60 * day,
    updatedAt: now - 1 * day,
  },
];

export const sampleCampaigns = [
  {
    id: 'camp-th-gut',
    clientId: 'client-th',
    name: 'Gut Health Revolution',
    objective: 'Brand Awareness',
    type: 'Organic',
    status: 'Active',
    platforms: ['Instagram', 'TikTok', 'YouTube'],
    startDate: new Date(now - 14 * day).toISOString().split('T')[0],
    endDate: new Date(now + 45 * day).toISOString().split('T')[0],
    budget: '8000',
    description: 'A 60-day content series educating audiences on gut health fundamentals, featuring expert interviews, myth-busting reels, and Bear Grylls personal testimonials. Driving awareness of the new probiotic supplement line.',
    keyMessages: [
      'Your gut is your second brain',
      'Science-backed probiotics',
      "Bear's daily gut health routine",
    ],
    targetMetrics: {
      reach: '500000',
      engagement: '4.5',
      conversions: '2000',
    },
    notes: 'Bear filming slots confirmed for week 3 and week 6. Dr. Sarah Collins confirmed as expert guest.',
    createdAt: now - 14 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: 'camp-th-summer',
    clientId: 'client-th',
    name: 'Summer Vitality Challenge',
    objective: 'Community Growth',
    type: 'Hybrid',
    status: 'Planning',
    platforms: ['Instagram', 'TikTok'],
    startDate: new Date(now + 30 * day).toISOString().split('T')[0],
    endDate: new Date(now + 90 * day).toISOString().split('T')[0],
    budget: '12000',
    description: 'A 60-day community challenge encouraging followers to adopt daily health habits. User-generated content campaign with weekly prizes. Paid amplification on best-performing UGC.',
    keyMessages: [
      '60 days to transform your vitality',
      'Join the tribe',
      'Small habits, massive results',
    ],
    targetMetrics: {
      reach: '1000000',
      engagement: '6.0',
      conversions: '5000',
    },
    notes: 'Need influencer shortlist by end of month. Prize budget separate from media spend.',
    createdAt: now - 7 * day,
    updatedAt: now - 3 * day,
  },
  {
    id: 'camp-w2-earth',
    clientId: 'client-w2',
    name: 'Earth Day Impact',
    objective: 'Brand Awareness',
    type: 'Hybrid',
    status: 'Active',
    platforms: ['Instagram', 'LinkedIn', 'X/Twitter'],
    startDate: new Date(now - 7 * day).toISOString().split('T')[0],
    endDate: new Date(now + 21 * day).toISOString().split('T')[0],
    budget: '5000',
    description: 'Multi-platform campaign around Earth Day highlighting Water2 impact metrics — clean water delivered, plastic bottles saved, communities served. Partnership content with NGO allies.',
    keyMessages: [
      '1 million litres delivered',
      'Your purchase creates change',
      'Clean water is a human right',
    ],
    targetMetrics: {
      reach: '300000',
      engagement: '5.0',
      conversions: '1000',
    },
    notes: 'NGO partner content approvals needed 5 days before publish. LinkedIn articles pre-drafted.',
    createdAt: now - 21 * day,
    updatedAt: now - 2 * day,
  },
  {
    id: 'camp-w2-b2b',
    clientId: 'client-w2',
    name: 'B2B Sustainability Leaders',
    objective: 'Lead Generation',
    type: 'Organic',
    status: 'Active',
    platforms: ['LinkedIn'],
    startDate: new Date(now - 30 * day).toISOString().split('T')[0],
    endDate: new Date(now + 60 * day).toISOString().split('T')[0],
    budget: '3000',
    description: 'LinkedIn thought leadership series targeting corporate sustainability officers. Weekly articles, case studies, and engagement with industry conversations. Goal: generate inbound B2B leads for office water solutions.',
    keyMessages: [
      'ESG compliance made simple',
      'Water sustainability for the modern office',
      'Measurable environmental impact',
    ],
    targetMetrics: {
      reach: '100000',
      engagement: '3.5',
      conversions: '50',
    },
    notes: "James to contribute personal articles bi-weekly. Need case study from Deloitte partnership.",
    createdAt: now - 30 * day,
    updatedAt: now - 5 * day,
  },
];

export const samplePosts = [
  {
    id: 'post-th-1',
    clientId: 'client-th',
    campaignId: 'camp-th-gut',
    platform: 'Instagram',
    type: 'Carousel',
    status: 'Scheduled',
    title: '5 Signs Your Gut Needs Attention',
    content: "Your gut talks to you every day — are you listening? 🧠\n\nSwipe through the 5 warning signs your gut microbiome is out of balance:\n\n1️⃣ Persistent bloating after meals\n2️⃣ Energy crashes in the afternoon\n3️⃣ Skin breakouts that won't clear\n4️⃣ Brain fog and poor concentration\n5️⃣ Irregular digestion patterns\n\nThe good news? Your gut can recover faster than you think. Science shows that targeted probiotics can shift your microbiome in as little as 2 weeks.\n\nTap the link in bio to learn about our clinically-tested probiotic blend.\n\n#GutHealth #Probiotics #TedsHealth #WellnessJourney #HealthyGut #Microbiome",
    scheduledDate: new Date(now + 1 * day).toISOString(),
    hashtags: ['GutHealth', 'Probiotics', 'TedsHealth', 'WellnessJourney'],
    notes: 'Carousel design in Canva - 6 slides. CTA slide links to product page.',
    createdAt: now - 3 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: 'post-th-2',
    clientId: 'client-th',
    campaignId: 'camp-th-gut',
    platform: 'TikTok',
    type: 'Reel/Short Video',
    status: 'Published',
    title: "Bear's Morning Gut Health Routine",
    content: "POV: You asked Bear Grylls what he does every morning for gut health ☀️\n\nSpoiler: it's simpler than you think.\n\n1. Warm water with lemon\n2. 10 minutes of movement\n3. Ted's Health Probiotic\n4. Fibre-rich breakfast\n\nThe man has survived the wild — his gut routine is built different.\n\n#BearGrylls #GutHealth #MorningRoutine #TedsHealth #Probiotics",
    scheduledDate: new Date(now - 5 * day).toISOString(),
    publishedDate: new Date(now - 5 * day).toISOString(),
    hashtags: ['BearGrylls', 'GutHealth', 'MorningRoutine', 'TedsHealth'],
    analytics: {
      views: 145000,
      likes: 8700,
      comments: 342,
      shares: 1200,
      saves: 2100,
    },
    notes: 'Filmed at Bear\'s farm. 45-second cut performed best in testing.',
    createdAt: now - 10 * day,
    updatedAt: now - 5 * day,
  },
  {
    id: 'post-th-3',
    clientId: 'client-th',
    campaignId: 'camp-th-gut',
    platform: 'YouTube',
    type: 'Long-Form Video',
    status: 'Draft',
    title: 'The Science of Gut Health ft. Dr. Sarah Collins',
    content: "In this episode, we sit down with Dr. Sarah Collins — one of the UK's leading gastroenterologists — to break down the science behind gut health.\n\nWe cover:\n- How your gut microbiome actually works\n- The link between gut health and mental health\n- Why most probiotics on the market don't work\n- What the research says about Ted's Health formulation\n- Simple daily habits for a healthier gut\n\nTimestamps:\n0:00 - Introduction\n2:15 - What is the microbiome?\n8:30 - Gut-brain connection\n15:00 - Probiotic myths debunked\n22:00 - The Ted's Health approach\n28:00 - Daily gut health tips",
    scheduledDate: new Date(now + 7 * day).toISOString(),
    hashtags: ['GutHealth', 'Science', 'DrSarahCollins', 'TedsHealth'],
    notes: 'Full interview recorded. Editing in progress — rough cut due Wednesday.',
    createdAt: now - 2 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: 'post-w2-1',
    clientId: 'client-w2',
    campaignId: 'camp-w2-earth',
    platform: 'Instagram',
    type: 'Image Post',
    status: 'Scheduled',
    title: 'Earth Day Impact Report',
    content: "This Earth Day, we're not just talking about change — we're measuring it. 🌍\n\n📊 Our 2025 Impact:\n💧 1.2 million litres of clean water delivered\n🏗️ 47 communities served\n♻️ 890,000 plastic bottles eliminated\n🤝 12 NGO partnerships active\n\nEvery Water2 bottle you choose creates a ripple effect that reaches communities thousands of miles away.\n\nThis isn't greenwashing. These are audited, verified numbers.\n\nLink in bio to read the full impact report.\n\n#EarthDay #CleanWater #Sustainability #Water2 #Impact",
    scheduledDate: new Date(now + 2 * day).toISOString(),
    hashtags: ['EarthDay', 'CleanWater', 'Sustainability', 'Water2'],
    notes: 'Infographic design approved by James. Use the new brand photography.',
    createdAt: now - 4 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: 'post-w2-2',
    clientId: 'client-w2',
    campaignId: 'camp-w2-b2b',
    platform: 'LinkedIn',
    type: 'Text Post',
    status: 'Published',
    title: 'Why Your Office Water Cooler Is an ESG Opportunity',
    content: "Most companies overlook the simplest ESG win sitting in their kitchen.\n\nYour office water solution is a daily touchpoint with every employee. It signals what your company values.\n\nPlastic bottles in the fridge? That's a message.\nA sustainable water system with measurable impact? That's a different message entirely.\n\nAt Water2, we've helped 200+ offices transition to sustainable hydration — and every litre funds clean water projects in communities that need it most.\n\nThe ROI isn't just environmental. Our corporate clients report:\n→ 23% improvement in employee sustainability perception scores\n→ Tangible ESG metrics for annual reporting\n→ Average 15% cost reduction vs. bottled water delivery\n\nIf your sustainability strategy doesn't include your water supply, it's incomplete.\n\nDM me to learn more about our corporate programme.",
    scheduledDate: new Date(now - 3 * day).toISOString(),
    publishedDate: new Date(now - 3 * day).toISOString(),
    hashtags: ['Sustainability', 'ESG', 'CorporateResponsibility', 'Water2'],
    analytics: {
      views: 12400,
      likes: 287,
      comments: 43,
      shares: 67,
      saves: 0,
    },
    notes: 'Strong engagement from target audience. Several DMs received.',
    createdAt: now - 7 * day,
    updatedAt: now - 3 * day,
  },
  {
    id: 'post-w2-3',
    clientId: 'client-w2',
    campaignId: 'camp-w2-earth',
    platform: 'X/Twitter',
    type: 'Thread',
    status: 'Approved',
    title: 'Earth Day Thread — 10 Facts About Water Inequality',
    content: "🧵 This Earth Day, let's talk about something that affects 2 billion people daily.\n\nA thread on water inequality — and what we can do about it.\n\n1/ 2.2 billion people lack access to safely managed drinking water. That's nearly 1 in 3 humans on Earth.\n\n2/ Women and girls in developing countries spend 200 million hours daily collecting water. That's time stolen from education, work, and rest.\n\n3/ Waterborne diseases kill more children under 5 than malaria, measles, and HIV combined.\n\n4/ Climate change is making it worse. By 2025, half the world's population will live in water-stressed areas.\n\n5/ The solution isn't complicated. Clean water infrastructure costs as little as £15 per person per year to maintain.\n\n6/ At @water2co, every product sold funds clean water projects. No gimmicks, audited impact.\n\n7/ In 2024, we delivered 1.2 million litres of clean water to 47 communities across 8 countries.\n\n8/ But corporate action matters most. 200+ offices now use Water2 — each one funding ongoing water projects.\n\n9/ You don't need to start a charity. You just need to make better purchasing decisions.\n\n10/ This Earth Day, choose products that create real impact. It's that simple.\n\nRT if you believe clean water is a right, not a privilege. 💧",
    scheduledDate: new Date(now + 3 * day).toISOString(),
    hashtags: ['EarthDay', 'WaterInequality', 'CleanWater', 'Water2'],
    notes: 'Thread format. Schedule tweets 3 minutes apart. Pin first tweet.',
    createdAt: now - 2 * day,
    updatedAt: now - 1 * day,
  },
];

export const sampleResearch = [
  {
    id: 'res-1',
    clientId: 'client-th',
    category: 'Competitor Analysis',
    title: 'AG1 Social Strategy Breakdown',
    content: "Analysed Athletic Greens (AG1) social media strategy across Instagram and TikTok.\n\nKey findings:\n- Heavy reliance on influencer partnerships (100+ active creators)\n- Average 3 posts/day on Instagram, 5 on TikTok\n- UGC reposts make up 40% of content\n- Morning routine content performs 3x better than product-focused posts\n- Their engagement rate has dropped from 4.2% to 2.8% over 6 months — possible audience fatigue\n- Price objection is the #1 comment theme\n\nOpportunity for Ted's Health:\n- Position as the science-first alternative (AG1 is lifestyle-first)\n- Exploit the price gap — our supplements are 30% cheaper\n- Bear Grylls gives us a differentiation AG1 can't match\n- Focus on depth of content over volume",
    tags: ['competitor', 'ag1', 'supplements', 'social-strategy'],
    priority: 'High',
    source: 'Manual analysis',
    createdAt: now - 15 * day,
    updatedAt: now - 15 * day,
  },
  {
    id: 'res-2',
    clientId: 'client-w2',
    category: 'Industry Trend',
    title: 'Corporate ESG Reporting Requirements 2026',
    content: "New EU CSRD requirements coming into force will mandate ESG reporting for companies with 250+ employees.\n\nKey implications for Water2 B2B strategy:\n- Companies actively seeking easy ESG wins to include in reports\n- Water/hydration is an overlooked category in most ESG audits\n- Opportunity to position Water2 as a turnkey ESG solution\n- Need to develop a standardised impact certificate for corporate clients\n- Competitor analysis shows no one else offering audited water impact metrics for office solutions\n\nRecommendation: Create a B2B landing page specifically targeting sustainability officers with ESG compliance angle. Include downloadable impact report template.",
    tags: ['esg', 'regulation', 'b2b', 'corporate'],
    priority: 'High',
    source: 'EU Commission website + Deloitte ESG report',
    createdAt: now - 10 * day,
    updatedAt: now - 10 * day,
  },
  {
    id: 'res-3',
    clientId: 'client-th',
    category: 'Audience Insight',
    title: 'Instagram Audience Deep Dive Q1 2026',
    content: "Pulled audience analytics for Ted's Health Instagram account.\n\nDemographics:\n- 67% Male, 33% Female\n- Top age: 25-34 (38%), then 35-44 (27%)\n- Top locations: London (12%), Manchester (6%), Birmingham (4%), New York (3%), Sydney (2%)\n- Peak activity: 7-8am and 6-8pm GMT\n\nContent performance (last 90 days):\n- Reels avg 45k views (up 23% QoQ)\n- Carousels avg 3.2% engagement (highest format)\n- Single images avg 1.8% engagement (declining)\n- Stories avg 8% completion rate\n\nTop performing themes:\n1. Bear Grylls personal content (4.5x avg engagement)\n2. Myth-busting health content (2.8x)\n3. Before/after transformations (2.3x)\n4. Product-focused posts (0.7x — below average)\n\nRecommendation: Increase Bear personal content and myth-busting reels. Reduce product-first posts. Carousels for educational content.",
    tags: ['instagram', 'analytics', 'audience', 'performance'],
    priority: 'Medium',
    source: 'Instagram Insights + Sprout Social export',
    createdAt: now - 5 * day,
    updatedAt: now - 5 * day,
  },
  {
    id: 'res-4',
    clientId: 'client-w2',
    category: 'Meeting Notes',
    title: 'Water2 Strategy Meeting — Q2 Planning',
    content: "Attendees: James Thornton (Water2), Olly, Ted\nDate: 2 April 2026\n\nAgenda items covered:\n\n1. Earth Day Campaign Status\n- All content created and approved\n- NGO partner videos received — awaiting final edit\n- Paid budget allocated: £2,000 Instagram, £1,500 LinkedIn\n- Target: 300k reach, 5% engagement\n\n2. B2B Pipeline\n- 12 inbound leads from LinkedIn campaign\n- 3 in proposal stage (Deloitte, Accenture, Unilever)\n- James to provide case study for Deloitte by 15 April\n\n3. Q2 Priorities\n- Launch corporate impact dashboard for clients\n- Summer festival partnerships (Glastonbury, Latitude)\n- Podcast sponsorship exploration\n- Refresh brand photography — current assets are 8 months old\n\n4. Budget\n- Q2 social budget confirmed: £15,000\n- Additional £5,000 approved for festival activations\n\nAction items:\n- Ted to draft festival partnership outreach (due: 10 April)\n- Olly to review and approve Earth Day final content (due: 5 April)\n- James to send Deloitte case study materials (due: 15 April)",
    tags: ['meeting', 'q2-planning', 'strategy', 'budget'],
    priority: 'Medium',
    source: 'Meeting notes',
    createdAt: now - 6 * day,
    updatedAt: now - 6 * day,
  },
];

export const sampleActivityFeed = [
  {
    id: 'act-1',
    type: 'post_published',
    message: "Published TikTok reel: Bear's Morning Gut Health Routine",
    clientId: 'client-th',
    entityId: 'post-th-2',
    timestamp: now - 5 * day,
  },
  {
    id: 'act-2',
    type: 'campaign_created',
    message: 'Created campaign: Earth Day Impact for Water2',
    clientId: 'client-w2',
    entityId: 'camp-w2-earth',
    timestamp: now - 21 * day,
  },
  {
    id: 'act-3',
    type: 'post_scheduled',
    message: "Scheduled Instagram carousel: 5 Signs Your Gut Needs Attention",
    clientId: 'client-th',
    entityId: 'post-th-1',
    timestamp: now - 3 * day,
  },
  {
    id: 'act-4',
    type: 'research_added',
    message: "Added research note: AG1 Social Strategy Breakdown",
    clientId: 'client-th',
    entityId: 'res-1',
    timestamp: now - 15 * day,
  },
  {
    id: 'act-5',
    type: 'post_published',
    message: 'Published LinkedIn post: Why Your Office Water Cooler Is an ESG Opportunity',
    clientId: 'client-w2',
    entityId: 'post-w2-2',
    timestamp: now - 3 * day,
  },
  {
    id: 'act-6',
    type: 'campaign_updated',
    message: 'Updated campaign: B2B Sustainability Leaders — added new target metrics',
    clientId: 'client-w2',
    entityId: 'camp-w2-b2b',
    timestamp: now - 5 * day,
  },
  {
    id: 'act-7',
    type: 'client_updated',
    message: "Updated client profile: Ted's Health — added new brand voice guidelines",
    clientId: 'client-th',
    entityId: 'client-th',
    timestamp: now - 2 * day,
  },
  {
    id: 'act-8',
    type: 'research_added',
    message: 'Added research note: Corporate ESG Reporting Requirements 2026',
    clientId: 'client-w2',
    entityId: 'res-2',
    timestamp: now - 10 * day,
  },
  {
    id: 'act-9',
    type: 'post_approved',
    message: 'Approved X thread: Earth Day Thread — 10 Facts About Water Inequality',
    clientId: 'client-w2',
    entityId: 'post-w2-3',
    timestamp: now - 1 * day,
  },
  {
    id: 'act-10',
    type: 'research_added',
    message: 'Added research note: Instagram Audience Deep Dive Q1 2026',
    clientId: 'client-th',
    entityId: 'res-3',
    timestamp: now - 5 * day,
  },
];

export const sampleSettings = {
  apiKey: '',
  userName: 'Olly W',
  businessName: 'Bear Grylls Ventures',
  defaultPlatforms: ['Instagram', 'TikTok', 'LinkedIn'],
  timezone: 'Europe/London',
  theme: 'dark',
};
